New Hos Clothing/Fixed Alinement Issues
Akira725/apocalypse pull request #19
Opened 2023-09-17 02:00 UTC by Catdere

-adds: 2 new clothing items 
-fixes: clothing sprites that would off centered should be fixed now
-rebalance: Head of Security now starts with the new Hudpatch a combination of the Sechud and Sec-Glasses
-rebalance: Head of Security now starts with the MMA Cap and New HOS's Winter Jacket

2023-09-17 02:21 UTC, Catdere commented
spooky felinid error

2023-09-17 16:42 UTC, VasilisThePikachu requested changes
Don't change default clothes, provide them in a closet/vending machine etc

2023-09-17 16:42 UTC, VasilisThePikachu commented on Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
> +    outerClothing: ClothingOuterArmorHopJacket
No change this

2023-09-17 16:42 UTC, VasilisThePikachu commented on Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
> +    head: ClothingHeadHatSyndieMAA
and tis

2023-09-17 16:42 UTC, VasilisThePikachu requested changes
Don't change default clothes, provide them

2023-09-17 22:37 UTC, VasilisThePikachu commented
Error is yours btw

2023-09-19 21:04 UTC, VasilisThePikachu commented
Make separate PR's you keep putting in stuff unrelated to this pr and need separate reviews

2023-10-01 06:27 UTC, closed without merging